name: internet_popup
description: A package for popUp message when Internet connection is off. Write one line to initialize a popUp when internet connection is turned off or connected but no internet.

version: 1.0.8+5
homepage: https://github.com/mehedidew/internet_popup

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.6


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.21.4
  flutter_lints: ^2.0.1


