name: internet_popup
description: A package for popUp message when Internet connection is off. Write one line to initialize a popUp when internet connection is turned off or connected but no internet.

version: 2.0.0
homepage: https://github.com/mehedidew/internet_popup

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.0.3


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.24.9
  flutter_lints: ^3.0.0


